name: Waka Readme

on:
  schedule:
    # To run on alternate days (i.e. Monday - Wednesday - Friday...) [0 2 * * 1/2]
    # Runs Every Day at 2AM
    - cron: '0 2 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_DAYS_OF_WEEK : "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO : "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROFILE_VIEWS: "False" 
          SHOW_COMMIT: "False"
